name: Rust Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        target: [x86_64-unknown-linux-gnu, x86_64-apple-darwin, x86_64-pc-windows-gnu]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-gnu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Create release directory
        run: mkdir -p releases/${{ matrix.target }}

      - name: Copy build artifacts
        run: cp target/${{ matrix.target }}/release/* releases/${{ matrix.target }}/

      - name: Archive release
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-${{ matrix.target }}-artifact
          path: releases/${{ matrix.target }}
